// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7h6zlWRVfA1DnpPyCRbNMouLyOoRrWVs',
    appId: '1:629045118682:web:69042f2ea7d09754fe87e3',
    messagingSenderId: '629045118682',
    projectId: 'home-travel-0262',
    authDomain: 'home-travel-0262.firebaseapp.com',
    storageBucket: 'home-travel-0262.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5IAsRDGm_boOrfaXplSyLM8ysHf5HwWc',
    appId: '1:629045118682:android:4e27cb2c5201a35bfe87e3',
    messagingSenderId: '629045118682',
    projectId: 'home-travel-0262',
    storageBucket: 'home-travel-0262.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjhJPmno9iAgpDev1A3gBV1holcPU7HVk',
    appId: '1:629045118682:ios:f7c6c21d6e3eb94bfe87e3',
    messagingSenderId: '629045118682',
    projectId: 'home-travel-0262',
    storageBucket: 'home-travel-0262.appspot.com',
    iosBundleId: 'com.example.mobileHomeTravel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjhJPmno9iAgpDev1A3gBV1holcPU7HVk',
    appId: '1:629045118682:ios:8fbb3b07b75d1d97fe87e3',
    messagingSenderId: '629045118682',
    projectId: 'home-travel-0262',
    storageBucket: 'home-travel-0262.appspot.com',
    iosBundleId: 'com.example.mobileHomeTravel.RunnerTests',
  );
}
